### ISSUE TITLE
Error from PostGres isn't very specific

### ISSUE THREAD

**Issue by normrider2001** [gas-buddy/configured-postgres-client#5]
I'm not sure if this an issue with the configured client or the underlying library.  But the PostGres errors aren't very specific.

I've seen this error on different types of errors that POSTGRES could send back.  (ie. PK constraint violations. or a Syntax error.).  Is there some way we can get more specific information.

`error: Failed to add message=Uncaught, unspecified "error" event. ([object Object]), stack=Error: Uncaught, unspecified "error" event. ([object Object
])
    at PgClient.emit (events.js:163:17)
    at /data/node_modules/@gasbuddy/configured-postgres-client/build/trackingClient.js:35:32
    at throw (native)
    at step (/data/node_modules/@gasbuddy/configured-postgres-client/build/trackingClient.js:7:191)
    at /data/node_modules/@gasbuddy/configured-postgres-client/build/trackingClient.js:7:402
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)`

**Comment by djMax** [comment]
That might be a logging problem as much as anything else. Can you get it in a debugger or otherwise inspect all the properties of the error object? Maybe there's something useful in there.

**Comment by normrider2001** [comment]
There is useful information in the error object.

`"error":{  
  "name":"error",
  "length":1241,
  "severity":"ERROR",
  "code":"22P02",
  "detail":"\"[\" must introduce explicitly-specified array dimensions.",
  "position":"116",
  "file":"arrayfuncs.c 
",
  "line":"272",
  "routine":"array_in"
}`

However in order to display it I would need to do something like 
`catch (error) {
      context.gb.logger.error('Failed to add', {
        message: error.context.error.detail,
        stack: error.stack,
      });`

I'm not sure if we could make the configured client return some useful information in the error message prior to re-throwing.

**Comment by djMax** [comment]
This is where gb-services wrapError comes in handy

**Comment by djMax** [comment]
Actually, I found out why this was happening. The emit of "error" throws if nobody is listening. So I've fixed that to emit "queryError" instead which does not throw if nobody is listening.
